#!/usr/bin/env python3
"""Rebuild audited shared vocabulary from exact, pinned Paintroid translation XML."""
import argparse
import hashlib
import json
import pathlib
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "translations"
RES = ROOT / "Paintroid/src/main/res"


def read_strings(path):
    return {node.get("name"): "".join(node.itertext()) for node in ET.parse(path).getroot() if node.tag == "string"}


def qualifier_and_tag(qualifier):
    # Crowdin's historical region labels encode Serbian scripts, not territories.
    special = {"values-sr-rCS": ("values-b+sr+Latn", "sr-Latn"),
               "values-sr-rSP": ("values-b+sr+Cyrl", "sr-Cyrl")}
    if qualifier in special:
        return special[qualifier]
    tag = qualifier.removeprefix("values-").replace("-r", "-")
    tag = {"iw": "he", "in": "id"}.get(tag, tag)
    return qualifier, tag


def generate():
    index = json.loads((DATA / "upstream-index.json").read_text())
    mapping = json.loads((DATA / "common-terms.json").read_text())
    base = read_strings(DATA / "upstream/values.xml")
    results = {}
    coverage = []
    tags = ["en"]
    for item in index["files"]:
        qualifier = pathlib.PurePosixPath(item["path"]).parent.name
        source = DATA / "upstream" / (qualifier + ".xml")
        raw = source.read_bytes()
        digest = hashlib.sha1(b"blob " + str(len(raw)).encode() + b"\0" + raw).hexdigest()
        if digest != item["blob_sha"]:
            raise ValueError(f"Upstream source bytes changed: {source}")
        if qualifier == "values":
            continue
        strings = read_strings(source)
        terms = {key: strings[old] for key, old in mapping.items()
                 if strings.get(old) and not strings[old].startswith("@")}
        distinct = sum(1 for key in terms if terms[key] != base.get(mapping[key]))
        output_qualifier, tag = qualifier_and_tag(qualifier)
        included = distinct > 0 or tag.startswith("en-")
        record = {"original_qualifier": qualifier, "language_tag": tag,
                  "reused_entries": len(terms), "entries_different_from_upstream_english": distinct,
                  "offered_in_app": included, "blob_sha": digest,
                  "source_sha256": hashlib.sha256(raw).hexdigest()}
        if included:
            tags.append(tag)
            lines = ['<?xml version="1.0" encoding="utf-8"?>',
                     '<!-- Shared vocabulary: Catrobat/Paintroid translators; AGPL-3.0-or-later.',
                     'Generated by tools/reuse_upstream_translations.py. See translations/README.md. -->',
                     '<resources>']
            for key, value in terms.items():
                # Android's numeric slider already supplies its own punctuation.
                if key == "ui_quality":
                    value = value.rstrip().rstrip(":：").rstrip()
                lines.append(f'    <string name="{key}">{escape(value)}</string>')
            lines += ['</resources>', '']
            target = RES / output_qualifier / "strings_upstream.xml"
            results[target] = "\n".join(lines)
            record["generated_resource"] = str(target.relative_to(ROOT))
        coverage.append(record)
    results[DATA / "coverage.json"] = json.dumps({"revision": index["revision"],
        "mapped_common_terms": len(mapping), "offered_language_count_including_english": len(tags),
        "coverage": coverage}, indent=2, ensure_ascii=False) + "\n"
    results[RES / "values/app_language_tags.xml"] = (
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated; see translations/README.md. -->\n'
        '<resources>\n    <string-array name="app_language_tags" translatable="false">\n' +
        ''.join(f'        <item>{tag}</item>\n' for tag in tags) +
        '    </string-array>\n</resources>\n')
    results[RES / "xml/app_locales.xml"] = (
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Partial vocabulary; see translations/README.md. -->\n'
        '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n' +
        ''.join(f'    <locale android:name="{tag}"/>\n' for tag in tags) + '</locale-config>\n')
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = generate()
    for path, expected in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text() != expected:
                raise SystemExit(f"Generated translation differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
    print(f"{'Verified' if args.check else 'Generated'} {len(outputs)} translation/language files")
